### ISSUE TITLE
Newer versions of boost libraries don't compile

### ISSUE THREAD

**Issue by stephenc87** [openpst/sahara#18]
Trying to compile with libboost-dev 1.71 on Ubuntu 20.10 will give me the error
`g++ -c -pipe -g -fPIC -Wall -Wextra -DDEBUG -DHEXDUMP_PORT_RX -DHEXDUMP_PORT_TX -I../../libopenpst -I. -I../include -I../lib/serial/include -I../lib/pugixml/src -IDEPENDPATH -I+= -I../../libopenpst -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o debug/obj/meid_converter.o ../src/util/meid_converter.cpp
In file included from ../src/util/meid_converter.cpp:27:
../include/util/meid_converter.h:32:10: fatal error: boost/uuid/sha1.hpp: No such file or directory
   32 | #include <boost/uuid/sha1.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~`

A quick google search showed me that this is happening with others
https://github.com/anura-engine/anura/issues/283

**Comment by stephenc87** [comment]
Coincidentally this is the wrong place, created the issue here https://github.com/openpst/libopenpst/issues/7
